name: ci

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1

      - name: Log versions
        run: |
          deno --version
      - name: Run deno fmt
        run: deno fmt --check --ignore=.claude/ --ignore=raw/ --ignore=archives/ --ignore=README.md

      - name: Run deno lint
        run: deno lint

      - name: Run deno test
        run: deno task test

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.repository, 'Sean529') &&
          startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
